### ISSUE TITLE
Documentation needed?

### ISSUE THREAD

**Issue by Leo-Ryu** [knorrie/btrfs-heatmap#12]
Hello,

My name is Leo and I’m a student at Brown-- During my break, I’ve been working on a platform for editable codebase documentation.

I came across this repo while browsing GitHub and noticed it lacked documentation. Do you mind if I create docs for your repo? I'm hoping it will be useful for your needs.

**Comment by knorrie** [comment]
Hi! Thanks for your interest in this project.

While there's quite some documentation about what this tool can do, or how to use it, you are right that the actual code itself (like, functions and classes) lacks any type of documentation.

Well, in the scripting howto (https://github.com/knorrie/btrfs-heatmap/blob/develop/doc/scripting.md) there's an explanation of function arguments for a few functions.

Can you explain a bit more about what your idea about this all would be?

When adding documentation to the code itself, I personally would prefer to use the sphinx style documentation that I also extensively use in the related python-btrfs project.

It's not high on my TODO list though. It would probably suddenly happen if someone shows up with actual questions about how it all works internally, while wanting to hack on the code (pragmatic reason why it did not happen yet).

For the related project, python-btrfs, I did actuall write ALL documentation for the public API of the library. https://python-btrfs.readthedocs.io/en/latest/genindex.html But in that case, it's really needed because the whole purpose of the library is that others can create things using the functions in there.

Knorrie

**Comment by knorrie** [comment]
Dikke doei
