### ISSUE TITLE
Running python script as root?

### ISSUE THREAD

**Issue by biggestsonicfan** [knorrie/btrfs-heatmap#13]
Greetings,

The script `btrfs-heatmap` (not ending with the typical python extension) requires pip module btrfs, however it's my understanding that pip should never be run as root. Installing the requirement (perhaps a requirements.txt should be added for a python project) as a non-root user does not give root privileges to this dependency.

Is there something simple I am missing, or do the dependencies require to be installed as root?

**Comment by biggestsonicfan** [comment]
Gonna assume this is a "wontfix"

**Comment by knorrie** [comment]
Hi, sorry for the delay.

Yes, the btrfs-heatmap script uses the Python btrfs library.

There's a bunch of different ways to install things. My personal recommendation would be to use packages that come with your favourite Linux distro that you're using, instead of using pip. The library is likely in there, as python3-btrfs or python-btrfs package, or something similar.

Hans
