### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by jorti** [knorrie/btrfs-heatmap#2]
Hi,

I would like to package this script in Fedora, but there is no indication of the license. Could you add a license and copyright header in the source code and the license text as a separate file?

Thank you.

**Comment by knorrie** [comment]
Hey,

Good question. I added a commit on top of develop branch to add license / copyright info. Since it's heavily depending on python-btrfs which will be integrating with btrfs kernel code closely in the future, it will be GPL (IANAL).

For the packaging... Next tagged versions of this program and python-btrfs will drop support for python 2. It's been educational to try supporting both 2 and 3, but the amount of headache is getting into the way of being able to quickly add more stuff.

Also, I created some initial debian packaging (debian branch), in which I put the program as /usr/sbin/btrfs-heatmap on the filesystem. There's also a man page in that branch, which needs some improvement with minimal parts from the online documentation added.

I have no good idea about including some more documentation into packaging for distros. I have put quite some time in writing the documentation already, because interpreting the data is not totally straightforward without knowing a few things about btrfs internals. The github markdown format is nice for easily creating some not too bad looking documentation, when you're not good at formatting things (and have no interest in spending time on it) but it's not something that makes sense to include in /usr/share/doc/btrfs-heatmap or such. Do you have any idea? I looked at a md->html converter, but all are a bit wonky. 

Thanks,
Knorrie

**Comment by jorti** [comment]
Thanks for the license, I'm going to submit it to Fedora:
https://bugzilla.redhat.com/show_bug.cgi?id=1425833

About the documentation, I'm not an expert, but many other projects use sphinx so they can generate man pages, text, and even the website. You can consider it.

Kind regards.

**Comment by knorrie** [comment]
Changes have been merged to master branch, v6.

Thanks
