### ISSUE TITLE
Feature request: Support image output to stdout

### ISSUE THREAD

**Issue by microraptor** [knorrie/btrfs-heatmap#7]
It would be awesome, if there is an stdout option for the output. So that you could pipe the PNG directly to an image viewer without having to manage a file:
```bash
sudo heatmap.py -qo - / | display - &
sudo heatmap.py -qo - / | feh - &
sudo heatmap.py -qo - / | catimg -
```
The last one would even display the image within the terminal.

It is currently possible to do something very similar using a temporary file, but it is not quite as elegant:
```bash
sudo heatmap.py --size 6 -o /tmp/htmp.png / && feh /tmp/htmp.png &
```

**Comment by knorrie** [comment]
Hi, nice idea, I like it!

Especially the pipe into ascii art viewer part is cool, since it provides a quick way to view the situation on a remote server while being logged in over ssh into a terminal (without having to rm the image file again etc). In combination with a helper program like 'timeout' and an infinite loop around it, you have a live refreshing self-updating image in the terminal, without writing an intermediate file.

What I did before while trying out things (on local computer) all the time was using an image viewer with inotify support like gthumb and then just overwriting the same file every time, having the viewer update automatically.

So, how to do this? When writing the png to stdout, all other text output has to be suppressed of course, but that's easy.

What's more difficult is that the png format is not "streaming-friendly" at all, since it has a length field which value we only know after writing all output. In the file writer code, I just jump back to that spot and then write the value, but that's obviously not possible when streaming to stdout:

https://github.com/knorrie/btrfs-heatmap/blob/d352ee139331da7ad2bb6aa3af674b20702492a2/heatmap.py#L584

So, instead it needs to generate everything in memory. That's not a big deal, since the memory needed is much less than the complete pixel grid which is already kept in memory in a very inefficient (but very convenient) way. :D

**Comment by microraptor** [comment]
I don't have much time right now, but I actually took a quick look at the code and did some testing. I noticed the problem with .seek() you mentioned, so the whole image needs to be buffered, and also that sys.stdout doesn't accept binary out of the box.

Using it in an SSH session and in a loop was my thought as well. It would be great to watch a defragmentation or balance operation going on with something like this:
`while :; do sudo heatmap.py --size 6 / -o - | catimg -; sleep 5; done`

Edit: fixed above command

**Comment by knorrie** [comment]
I tried catimg, it does not accept data from stdin. Do you have another catimg than I found, or didn't you try catimg - < pngfile yet?

I do like the result of what catimg shows more than cacaview or asciiview by the way. Unfortunately, it's also taking its time to produce it.

**Comment by knorrie** [comment]
Oh wait, nevermind, there's a script and a C version (with stdin support). Bedtime, apparently. :)

**Comment by microraptor** [comment]
Exactly, the C version works with stdin and is pretty fast. The ANSI output of it makes a lot more sense then the ASCII symbols of the other tools.

**Comment by microraptor** [comment]
The images look also the best if the the resolution of the catimg image is a power of two. So either by using something like `-w 128` with catimg or `--size 6` with heatmap.py in order to fit it inside the terminal.

**Comment by knorrie** [comment]
Oh, and catimg is also in Debian now. Great! I was just looking around on a Stretch system yesterday and didn't find it, but it's in Buster. Let me try to create a PoC branch first so that you can play around with it. I'm thinking about just using a dirty list to write into and some duck typing for creating a yolo memory buffer and not having to put workarounds in the 30 line png generator that I was so proud of. ;-]

**Comment by knorrie** [comment]
Hey! You can try out the develop branch!

This is awesome. I will also add this to the documentation.

**Comment by microraptor** [comment]
Thanks, this is great! The pipe to `| catimg -` and `| feh - &` works perfectly for me!

**Comment by knorrie** [comment]
Ah, I'll also add feh as suggestion in the documentation yes.
