### ISSUE TITLE
Suggestion: Use colors for different RAID levels

### ISSUE THREAD

**Issue by endolith** [knorrie/btrfs-heatmap#8]
It would be nice to be able to see the single data being converted to raid1, etc.

**Comment by knorrie** [comment]
Hi, it took a while to answer this. :) My free time so far in 2019 has mainly been eaten by non-computer-related things.

Colors are fun. But, they're also a difficult thing. On the Extent level pictures documentation page you can see the colors that I did choose for the extent-level metadata pictures, where I had to choose a color for every possible value. I experimented with all kinds of things and ended up with a bunch of "soft" pastel colors to use, because just naively choosing blue! red! yellow! results in pictures that only really hurt your eyes and do not help at all.

The main purpose of the default chunk-level picture you get is to show if the physical disk space is used efficiently, or if there's a lot of unused space hidden in allocated chunks. Using colors distracts from that, so it will not be a default.

However, it's definitely a fun idea to be able to pick colors for things to e.g. like you say, be able to see stuff move around in specific scenarios. This can be converting from single to raid1, but it can also be moving data that has the same profile from disk1 to disk2 (that would probably be the next feature request from another user)...

I'd like to experiment a bit to make it possible to use colors for things. The idea I have here is to create a branch and first add the possibility to define colors for specific profiles, so that you can start playing around with it and see results and if they make you happy or not. It'll probably be a <10 line patch in the code.

**Comment by knorrie** [comment]
In the develop branch, I added a commit "Allow setting colors for specific bg flags". Instead of always stripping off the profile bits and only searching for type color (data, metadata, mixed), it will now first try to see if there's a color defined for the full flags, so e.g. DATA|RAID1.

In the dev_extent_colors dictionary inside the program, adding a value like...
```
btrfs.BLOCK_GROUP_DATA | btrfs.BLOCK_GROUP_RAID1: (0x7f, 0x00, 0xff),
```
...will make DATA|RAID1 show up as purple, while normal 'single' DATA will still be white.

So, at least you can play around with it now and for example create a nice timelapse video of converting. I'm curious to see it. :-)

I have no idea yet if and how this will be made available without changing the script itself later.
